###get all categories
GET localhost:3000/api/categories
X-API-KEY: RAHASIA
Accept: application/json

###create new category
POST localhost:3000/api/categories
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Computer"
}

### get category by id
GET localhost:3000/api/categories/2
Accept: application/json


###update category
PUT localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json

{
  "name": "Gadget update"
}


###delete category
DELETE localhost:3000/api/categories/1
Accept: application/json